demo/authorization/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('authorization/', include('authorization.urls')),
]

demo/mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
]

demo/authorization/models.py
from django.contrib.auth.models import AbstractUser, Permission, Group
from django.db import models


class CustomUser(AbstractUser):
    avatar = models.ImageField('Аватар', upload_to='serveruploads',
                               default='serveruploads/placeholder.jpg')
    address = models.CharField(verbose_name='Адресс проживания', max_length=255, blank=True, null=True)
    phone_number = models.CharField(verbose_name='Номер телефона', max_length=12, null=True)
    birthday = models.DateField(verbose_name='Дата рождения', null=True, blank=True)

    groups = models.ManyToManyField(Group, related_name='customuser_set', blank=True, verbose_name='Groups')

    user_permissions = models.ManyToManyField(
        Permission,
        related_name='customuser_set',
        blank=True,
        verbose_name='User permissions',
        help_text='Specific permissions for this user.',
    )

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = 'Пользователи системы'

demo/mainapp/models.py
from django.db import models

# Create your models here.

demo/authorization/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    address = forms.CharField(max_length=255, required=False)
    phone_number = forms.CharField(max_length=12, required=False)
    birthday = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'address', 'phone_number',
                  'birthday']


class CustomUserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'phone_number', 'birthday']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['birthday'].widget.attrs.update({'class': 'form-control', 'type': 'date'})


class CustomUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Имя пользователя'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Пароль'})

    class Meta:
        model = CustomUser
        fields = ['username', 'password']

demo/authorization/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserLoginForm, CustomUserEditForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('profile')
        else:
            print(form.errors)
    else:
        form = CustomUserCreationForm()

    return render(request, 'register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(request, request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('profile')
    else:
        form = CustomUserLoginForm()
    return render(request, 'login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')  # Перенаправление после выхода


@login_required
def profile_view(request):
    return render(request, 'profile.html')


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = CustomUserEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = CustomUserEditForm(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form})

demo/mainapp/views.py
from django.shortcuts import render


def mainpage(request):
    return render(request, 'mainpage.html')

demo/authorization/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title mb-4">Редактирование профиля</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

demo/authorization/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="registration-form container-fluid d-flex align-items-center justify-content-center" style="height: 100vh">
    <div class="row col-6">
        <div class="col-12">
            <div class="login d-flex align-items-center justify-content-center py-5">
                <div class="container">
                    <h3 class="login-heading text-center mb-4">Добро пожаловать!</h3>
                    <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}

                        <div class="mb-3">
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger" role="alert">
                                    {{ form.non_field_errors }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username" name="username" placeholder="Имя пользователя">
                            <label for="id_username">Имя пользователя</label>
                            {% if form.username.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}" id="id_password" name="password" placeholder="Пароль">
                            <label for="id_password">Пароль</label>
                            {% if form.password.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="d-grid">
                            <button class="btn btn-lg btn-login text-uppercase fw-bold mb-2" type="submit">Войти</button>
                            <a href="{% url 'register' %}" class="reg-text text-center">Нет аккаунта? Зарегистрируйтесь!</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

demo/authorization/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<section class="profile">
    <div class="container d-flex align-items-center justify-content-center vh-100">
        <div class="card" style="width: 18rem">
            <div class="card-body">
                <h5 class="card-title">Имя пользователя: {{ user.username }}</h5>
                <div class="card__text">
                    <p class="card-text">Email: {{ user.email }}</p>
                    <p class="card-text">Номер телефона: {{ user.phone_number }}</p>
                    <p class="card-text">Адрес: {{ user.address }}</p>
                    <p class="card-text">Дата рождения: {{ user.birthday }}</p>
                </div>
                <br>
            <a href="{% url 'edit_profile' %}" class="btn btn-outline-primary">Редактировать профиль</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

demo/authorization/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="registration-form container-fluid d-flex align-items-center justify-content-center" style="height: 100vh">
    <div class="row col-6">
        <div class="col-12">
            <div class="login d-flex align-items-center justify-content-center py-5">
                <div class="container">
                    <h3 class="login-heading text-center mb-4">Добро пожаловать!</h3>
                    <form method="post" action="{% url 'register' %}">
                        {% csrf_token %}

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username" name="username" placeholder="Имя пользователя">
                            <label for="id_username">Имя пользователя</label>
                            {% if form.username.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}" id="id_password1" name="password1" placeholder="Пароль">
                            <label for="id_password1">Пароль</label>
                            {% if form.password1.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.password1.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}" id="id_password2" name="password2" placeholder="Подтвердите пароль">
                            <label for="id_password2">Подтвердите пароль</label>
                            {% if form.password2.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.password2.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control {% if form.first_name.errors %}is-invalid{% endif %}" id="id_first_name" name="first_name" placeholder="Имя">
                            <label for="id_first_name">Имя</label>
                            {% if form.first_name.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.first_name.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control {% if form.last_name.errors %}is-invalid{% endif %}" id="id_last_name" name="last_name" placeholder="Фамилия">
                            <label for="id_last_name">Фамилия</label>
                            {% if form.last_name.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.last_name.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email" name="email" placeholder="name@example.com">
                            <label for="id_email">Email</label>
                            {% if form.email.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control {% if form.address.errors %}is-invalid{% endif %}" id="id_address" name="address" placeholder="Адрес проживания">
                            <label for="id_address">Адрес проживания</label>
                            {% if form.address.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.address.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}" id="id_phone_number" name="phone_number" placeholder="Номер телефона">
                            <label for="id_phone_number">Номер телефона</label>
                            {% if form.phone_number.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.phone_number.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-floating mb-3">
                            <input type="date" class="form-control {% if form.birthday.errors %}is-invalid{% endif %}" id="id_birthday" name="birthday">
                            <label for="id_birthday">Дата рождения</label>
                            {% if form.birthday.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.birthday.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="d-grid">
                            <button class="btn btn-lg btn-login text-uppercase fw-bold mb-2" type="submit">Зарегистрироваться</button>
                            <a href="{% url 'login' %}" class="reg-text text-center">Уже есть аккаунт? Войдите!</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

demo/mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Магазин цветов "Plantify Garden"</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
</head>
<body>
<header class="header">
    <div class="container-lg">
        <div class="header-content">
            <nav><!-- начало залупы с кнопками навигации по сайту -->
                <ul class="nav">

                    <!-- начало лого (для даунов) -->
                </ul><!-- конец залупы с кнопками навигации по сайту -->
            </nav>
            <div class="logo"><a href="{% url 'mainpage' %}"><img src="{% static 'img/logo.svg' %}" alt=""></a></div>
            <!-- конец лого (для даунов) -->
            <ul class="nav-icons"><!-- иконка юзера (для даунов) -->
                <li><a href="{% url 'profile' %}"><img src="{% static 'img/user.svg' %}" alt=""></a></li><!-- иконка корзины (для даунов) -->
                <li><form class="d-flex form-inline my-2 my-lg-0">
                  <input
                    class="form-control mr-sm-2"
                    type="search"
                    placeholder="Поиск товара"
                    aria-label="Поиск товара"
                  />
                </form></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">{{user.username}} (Выйти)</a></li>
                {% endif %}
                <li><a href=""><img src="{% static 'img/cart.svg' %}" alt=""></a></li>
            </ul>
        </div>
    </div>
</header>
{% block content %}
{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script src="{% static 'js/main.min.js' %}"></script>
</html>

demo/mainapp/templates/mainpage.html
{% extends 'base.html' %}
{% block content %}
<p>Бебра!</p>
{% if user.is_authenticated %}
<a href="{% url 'profile' %}">{{user.username}} (Профиль)</a>
<a href="{% url 'logout' %}">Выйти</a>
{% else %}
<a href="{% url 'login' %}">Войти</a>
{% endif %}
{% endblock %}